# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_five.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(699, 626)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.dock_login = QtWidgets.QDockWidget(Dialog)
        self.dock_login.setMaximumSize(QtCore.QSize(199, 200))
        self.dock_login.setObjectName("dock_login")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dockWidgetContents)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_login = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_login.setObjectName("label_login")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.line_login = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_login.setText("")
        self.line_login.setObjectName("line_login")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.line_login)
        self.label_passwd = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_passwd.setObjectName("label_passwd")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_passwd)
        self.line_passwd = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_passwd.setText("")
        self.line_passwd.setObjectName("line_passwd")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.line_passwd)
        self.formLayout_entry = QtWidgets.QFormLayout()
        self.formLayout_entry.setObjectName("formLayout_entry")
        self.btn_sign_in = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_sign_in.setObjectName("btn_sign_in")
        self.formLayout_entry.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_sign_in)
        self.btn_sign_up = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.formLayout_entry.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btn_sign_up)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.formLayout_entry)
        self.dock_login.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dock_login, 0, 0, 1, 1)
        self.input_panel = QtWidgets.QWidget(Dialog)
        self.input_panel.setMinimumSize(QtCore.QSize(681, 131))
        self.input_panel.setObjectName("input_panel")
        self.btn_send = QtWidgets.QPushButton(self.input_panel)
        self.btn_send.setGeometry(QtCore.QRect(580, 100, 83, 23))
        self.btn_send.setObjectName("btn_send")
        self.textEdit = QtWidgets.QTextEdit(self.input_panel)
        self.textEdit.setGeometry(QtCore.QRect(0, 10, 671, 81))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.input_panel, 2, 0, 1, 3)
        self.btn_hide = QtWidgets.QRadioButton(Dialog)
        self.btn_hide.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_hide.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_hide.setObjectName("btn_hide")
        self.gridLayout.addWidget(self.btn_hide, 0, 1, 1, 1)
        self.login = QtWidgets.QLabel(Dialog)
        self.login.setMaximumSize(QtCore.QSize(100, 16777215))
        self.login.setText("")
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(671, 271))
        self.tabWidget.setMaximumSize(QtCore.QSize(675, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("hello")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 671, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 3)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_login.setText(_translate("Dialog", "Login"))
        self.label_passwd.setText(_translate("Dialog", "Password"))
        self.btn_sign_in.setText(_translate("Dialog", "Sign In"))
        self.btn_sign_up.setText(_translate("Dialog", "Sign Up"))
        self.btn_send.setText(_translate("Dialog", "Enter"))
        self.btn_hide.setText(_translate("Dialog", "Hide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Hello Window"))

